[package]
name = "advent2023"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
cached = "0.46.1"
futures = "0.3.29"
itertools = "0.12.0"
linya = "0.3.0"
num = "0.4.1"
pathfinding = "4.6.0"
rayon = "1.8.0"
tokio = { version = "1.34.0", features = ["full"] }
